package com.robert.today.csdn_client.database.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.robert.today.csdn_client.database.dao.Log;

import com.robert.today.csdn_client.database.dao.LogDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig logDaoConfig;

    private final LogDao logDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        logDaoConfig = daoConfigMap.get(LogDao.class).clone();
        logDaoConfig.initIdentityScope(type);

        logDao = new LogDao(logDaoConfig, this);

        registerDao(Log.class, logDao);
    }
    
    public void clear() {
        logDaoConfig.getIdentityScope().clear();
    }

    public LogDao getLogDao() {
        return logDao;
    }

}
