package com.robert.today.csdn_client.database.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOG.
 */
public class Log {

    private Long id;
    /** Not-null value. */
    private String tag;
    /** Not-null value. */
    private String content;
    private java.util.Date date;

    public Log() {
    }

    public Log(Long id) {
        this.id = id;
    }

    public Log(Long id, String tag, String content, java.util.Date date) {
        this.id = id;
        this.tag = tag;
        this.content = content;
        this.date = date;
    }

    public Log(String tag, String content, java.util.Date date) {
        this.tag = tag;
        this.content = content;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTag() {
        return tag;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
